// <auto-generated />
namespace ZeroWaste.SharePortal.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddIconDescription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddIconDescription));
        
        string IMigrationMetadata.Id
        {
            get { return "201309300531586_AddIconDescription"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
